spring:
  jpa:
    generate-ddl: true
    show-sql: true

  datasource:
    platform: h2
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    username: sa
    password:

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  info:
    git:
      mode: full
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true